:a: 1
:abbr: 0
:acronym: 0
:address: 0
:applet: -1
:area: 0
:b: 1
:base: 0
:basefont: -1
:bdo: 0
:big: 1
:blockquote: 0
:body: 0
:br: 0
:button: 0
:caption: 1
:center: -1
:cite: 0
:code: 0
:col: 0
:colgroup: 0
:dd: 0
:del: 0
:dfn: 0
:dir: -1
:div: 0
:dl: 0
:dt: 0
:em: 0
:fieldset: 0
:font: 0
:form: 0
:frame: 0
:frameset: 0
:h1: 10
:h2: 8
:h3: 6
:h4: 5
:h5: 4
:h6: 3
:head: 0
:hr: 0
:html: 0
:i: 1
:iframe: 0
:img: 0
:input: 0
:ins: 0
:isindex: 0
:kbd: 0
:label: 1
:legend: 0
:li: 0
:link: 0
:map: 0
:menu: -1
:meta: 0
:noframes: 0
:noscript: 0
:object: 0
:ol: 0
:optgroup: 0
:option: 0
:p: 1
:param: 0
:pre: 0
:q: 0
:s: -1
:samp: 0
:script: 0
:select: 0
:small: 0
:span: 0
:strike: 0
:strong: 2
:style: 0
:sub: 0
:sup: 0
:table: 0
:tbody: 0
:td: 0
:textarea: 0
:tfoot: 0
:th: 0
:thead: 0
:title: 20
:tr: 0
:tt: 0
:u: 1
:ul: 0
:var: 0
